services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: devops_j
      POSTGRES_PASSWORD: clave
      POSTGRES_DB: devops_journey
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devops_j -d devops_journey"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://devops_j:clave@db:5432/devops_journey
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
